### ISSUE TITLE
Saknar Wikipedia länk i IFKDB

### ISSUE THREAD

**Issue by salgo60** [salgo60/ifkdb#1]
* [x] [Johan-Bångsbo_944](https://ifkdb.se/spelare/Johan-B%C3%A5ngsbo_944) -  wiki [Johan_Bångsbo](https://sv.wikipedia.org/wiki/Johan_B%C3%A5ngsbo)
* [x] [Hussein-Carneil_941](https://ifkdb.se/spelare/Hussein-Carneil_941) - wiki [Hussein Carneil](https://sv.wikipedia.org/wiki/Hussein_Carneil)
* [x] [Adam Ingi Benediktsson_937](https://ifkdb.se/spelare/Adam%2BIngi-Benediktsson_937) -  wiki [Adam Ingi Benediktsson](https://sv.wikipedia.org/wiki/Adam_Ingi_Benediktsson#K%C3%A4llor)
* [x] [Rolf-Almqvist_16](https://ifkdb.se/spelare/Rolf-Almqvist_16) - wiki [Rolf Almqvist_(1928 2008)](https://sv.wikipedia.org/wiki/Rolf_Almqvist_(1928%E2%80%932008))
* [x] [Mats-Ola-Carlsson_150](https://ifkdb.se/spelare/Mats-Ola-Carlsson_150) - wiki [Mats-Ola Carlsson](https://sv.wikipedia.org/wiki/Mats-Ola_Carlsson)
* [x] [Filip Ambrož](https://ifkdb.se/spelare/Filip-Ambro%C5%BE_931) - [Filip_Ambroz](https://sv.wikipedia.org/wiki/Filip_Ambroz)
* [x] [Linus-Carlstrand_946](https://ifkdb.se/spelare/Linus-Carlstrand_946) 
* [x] [Felix-Eriksson_948](https://ifkdb.se/spelare/Felix-Eriksson_948)
* [x] [Arbnor-Mucolli_966](https://ifkdb.com/player/Arbnor-Mucolli_966)
* [x] [Adam-Carlén_958](https://ifkdb.com/player/Adam-Carl%C3%A9n_958)
* [x] [#24 Abundance Salaou](https://ifkdb.com/player/Abundance-Salaou_949)
* [x] [Alai Ghasem](https://ifkdb.com/player/Alai-Ghasem_17)

**Comment by salgo60** [comment]
Lite dumt att jag snurrar runt med "egen på hittade id:n" i WIkidata

Det finns en [hub](https://tools.wmflabs.org/hub/) som en kill gjort som gör att man kan ta ett extern id och hoppa till WIkidata med det ---- tror den måste startas om för att läsa in nya egenskaper....
* ex egenskap P11905
* värde [Dag-Magnusson_486](https://ifkdb.se/spelare/Dag-Magnusson_486)
* --> https://hub.toolforge.org/P11904:Dag-Magnusson_486?property=P7704&site=wd

---- 
Exempel äldre WD egenskap som kanske fungerar
* ex egenskap footballdatabase = P2574
* värde [16959](https://www.national-football-teams.com/de/player/16959.html)
* --> https://hub.toolforge.org/P2574:16959?site=wd
   * https://hub.toolforge.org/P2574:16959?lang=sv  
   * https://hub.toolforge.org/P2574:16959?site=wd
   * https://hub.toolforge.org/P2574:16959?lang=de 
   * https://hub.toolforge.org/P2574:16959?property=P18
   *  * https://hub.toolforge.org/P2574:16959?site=svwiki
   
----
hämta json ---> skulle kunna användas för att kolla att WD och IFKDB är i synk
* https://hub.toolforge.org/P2574:16959?lang=en&format=json
* https://hub.toolforge.org/P2574:16959?lang=sv&format=json
*

**Comment by ifkdb** [comment]
* [X]  [Linus-Carlstrand_946](https://ifkdb.se/spelare/Linus-Carlstrand_946)
 * [X]  [Felix-Eriksson_948](https://ifkdb.se/spelare/Felix-Eriksson_948)
 * [X]  [Arbnor-Mucolli_966](https://ifkdb.com/player/Arbnor-Mucolli_966) (danska)
 * [X]  [Adam-Carlén_958](https://ifkdb.com/player/Adam-Carl%C3%A9n_958)
 * [X]  [#24 Abundance Salaou](https://ifkdb.com/player/Abundance-Salaou_949)
 * [X]  [Alai Ghasem](https://ifkdb.com/player/Alai-Ghasem_17)
